### ISSUE TITLE
Left-align non-lede content

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/themejam.gatsbyjs.org#16]
It makes sense for this paragraph to be centered:

<img width="1106" alt="Screen Shot 2019-07-02 at 6 06 55 PM" src="https://user-images.githubusercontent.com/163561/60556024-35cb9b00-9cf4-11e9-9492-5fe6cde20c26.png">

It is _not_ super legible to have the contest rules centered:

<img width="1116" alt="Screen Shot 2019-07-02 at 6 07 54 PM" src="https://user-images.githubusercontent.com/163561/60556058-55fb5a00-9cf4-11e9-8ba2-c92c535b78b6.png">

My proposal here is to:

- [ ] Add a `lede` block for that home page content (this should also probably be a larger font size, but we can deal with that later)
- [ ] Make the rest of the content on the site left-aligned by default

**Comment by gillkyle** [comment]
I'll get working on this
