### ISSUE TITLE
Possible rule on theme submissions

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/themejam.gatsbyjs.org#24]
So I was thinking that a good rule to be put in place for the ThemeJam is to maybe restrict previously made themes from being entered. I'm thinking this as themes have been in a beta state for a few months and with that, I wouldn't want people to have an advantage in this over someone who is just learning about Themes when the event begins.

cc: @jlengstorf @gillkyle

**Comment by lannonbr** [comment]
Thinking about it further though the contestants have about a month to make their theme, so there isn't too much of a time crunch.

I can see it be okay if either this is put in place or not

**Comment by jlengstorf** [comment]
Thanks for bringing this up, @lannonbr. @gatsbyjs/themes-core any thoughts on this? I could go either way.

**Comment by amberleyromo** [comment]
After discussing with the team, we think we don't need to enforce a submission window. Leaving it open will incentivize any folks who created themes in the experimental phase to update, and be adherent to the qualities we're looking for (code quality, a11y, etc) and to be tagged properly.

Thanks for your thoughtfulness in bringing this up, though!
