### ISSUE TITLE
Add social sharing metadata

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/themejam.gatsbyjs.org#9]
We need to add social sharing metadata. We can use this component and probably lift it straight across.

https://github.com/jlengstorf/marisamorby.com/blob/a817a02ba482573ca7a56b75dbe2a43d504bfee0/packages/gatsby-theme-blog-sanity/src/components/seo.js#L40-L52

**Comment by gillkyle** [comment]
Addressed by #12
